[package]
name = "pulse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["full"] }
